import { Timestamp } from "firebase-admin/firestore";

export type UserType = "Employee" | "Owner" | "Administrator" | "Financer"; // types of users

export interface User {
  id?: string; // generated by firestore
  clerkUserId: string;
  firstName: string;
  lastName: string;
  email: string;
  twoFactorEnabled?: boolean; // new for tracking status
  userType: UserType; 
  isSubscribed: boolean;
  province: string;
  companyId?: string; // will reference company
  companyName?: string;
  createdAt: Date;
  updatedAt: Date;
}

export interface Company {
  id?: string;
  name: string;
  ownerId: string; // references user
  s3BucketName: string; 
  createdAt: Date;
  updatedAt: Date;
  documents: Document[]; 
}

export interface Chat {
  id?: string;
  userId: string; // references user
  companyId?: string; // null if public chat
  createdAt: Date;
  updatedAt: Date;
  messages?: Message[]; // array of messages in the chat
  title?: string; // optional title for the chat
}

export interface Message {
  id?: string;
  isFromUser: boolean;
  createdAt: Date;

  // for user messages and (legacy) storing bot messages
  content?: string;

  // bot responses and sources (new)
  publicResponse?: string;
  privateResponse?: string;

  publicSources?: Link[]
  privateSources?: Link[]

  // bot sources (legacy)
  sources?: Link[];
}

export interface Document {
  id?: string;
  fileUrl: string;
  fileName?: string;
  uploadDate: Date;
  isPublic: boolean;
  province: string;

}

export interface Link {
  title: string;
  url: string;
  page?: number
}

export interface Invitation {
  id?: string;
  email: string;
  companyId: string;
  companyName: string;
  inviterId: string; // owner that sent the invite
  status: "pending" | "accepted" | "rejected";
  createdAt: Date;
  updatedAt: Date;
}

export interface PopularQuestion {
  id?: string
  province: string
  company: string
  text: string
  createdAt?: Timestamp
}