export type UserType = "Employee" | "Owner" | "Administrator" | "Financer"; // types of users

export interface User {
  id?: string; // generated by firestore
  firstName: string;
  lastName: string;
  primaryEmail: string;
  backupEmail?: string;
  userType: UserType; 
  isSubscribed: boolean;
  province: string;
  companyId?: string; // will reference company
  createdAt: Date;
  updatedAt: Date;
}

export interface Company {
  id?: string;
  name: string;
  ownerId: string; // references user
  createdAt: Date;
  updatedAt: Date;
}

export interface Chat {
  id?: string;
  userId: string; // references user
  companyId?: string; // null if public chat
  createdAt: Date;
  updatedAt: Date;
  messages?: Message[]; // array of messages in the chat
  title?: string; // optional title for the chat
}

export interface Message {
  id?: string;
  content: string;
  isFromUser: boolean;
  sources?: string[]; // for any cited sources
  createdAt: Date;
}

export interface Document {
  id?: string;
  companyId: string; // references the company
  fileUrl: string;
  description?: string;
  uploadDate: Date;
  isPublic: boolean;
}